### ISSUE TITLE
posters

### ISSUE THREAD

**Issue by MartijnKaijser** [paddycarey/plugin.video.mmabrowser#1]
Some skins like Aeon Nox have an option to force the use of poster.jpg and banner.jpg tvshows. When switched on no posters are shown. When 'use poster.jpg' is switched off the posters are shown.

Possible solution. Put every fighter/organization in it's own subfolder using fighter/organization ID and user poster.jpg and banner.jpg

**Comment by paddycarey** [comment]
I had thought about that but wasn't sure how i'md do it. Where exactly does nox look for the posters when you turn the option on?
----- Original message -----

**Comment by MartijnKaijser** [comment]
$INFO[ListItem.Path,,poster.jpg]

So in some way you have to set the path to then

**Comment by MartijnKaijser** [comment]
http://paste.ubuntu.com/780316/
It tries to get the posters from the main folder.
